export const mockAdminIssues = [
  {
    id: 'adm-1',
    title: 'Massive pothole on Main Street',
    category: 'pothole',
    status: 'reported',
    location: 'Main St & 4th Ave',
    upvotes: 45,
    commentsCount: 12,
    department: 'Public Works',
    timestamp: '2023-10-24',
    description: 'There is a huge pothole spanning almost the entire left lane. Several cars have hit it hard. Needs immediate filling before someone gets into a serious accident.',
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'adm-2',
    title: 'Overflowing dumpster behind complex',
    category: 'garbage',
    status: 'acknowledged',
    location: 'Sector 4, Market area',
    upvotes: 32,
    commentsCount: 5,
    department: 'Sanitation',
    timestamp: '2023-10-23',
    description: 'The main commercial dumpster hasn’t been emptied in over a week. Garbage is spilling into the street and attracting pests. Smells terrible.',
    imageUrl: 'https://images.unsplash.com/photo-1605600659873-d808a1d84f8c?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'adm-3',
    title: 'Burst pipe flooding the sidewalk',
    category: 'water',
    status: 'inProgress',
    location: 'Elm Street & 2nd Ave',
    upvotes: 89,
    commentsCount: 24,
    department: 'Water Board',
    timestamp: '2023-10-22',
    description: 'Water is gushing out of a cracked pipe under the pavement. It’s flooding the pedestrian walkway and freezing over at night, making it very dangerous.',
    imageUrl: 'https://images.unsplash.com/photo-1542037104857-ffbb0b9155fb?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: 'adm-4',
    title: 'Streetlights out for 3 blocks',
    category: 'streetlight',
    status: 'resolved',
    location: 'Oak Drive, North side',
    upvotes: 12,
    department: 'Electrical',
    timestamp: '2023-10-20',
  },
  {
    id: 'adm-5',
    title: 'Fallen tree blocking intersection',
    category: 'other',
    status: 'reported',
    location: 'Pine Blvd & 5th St',
    upvotes: 67,
    department: 'Parks & Rec',
    timestamp: '2023-10-25',
  },
  {
    id: 'adm-6',
    title: 'Illegal dumping near the river',
    category: 'garbage',
    status: 'inProgress',
    location: 'River Road, East bank',
    upvotes: 104,
    department: 'Sanitation',
    timestamp: '2023-10-18',
  },
  {
    id: 'adm-7',
    title: 'Severe road subsidence',
    category: 'pothole',
    status: 'acknowledged',
    location: 'Highway 9 off-ramp',
    upvotes: 56,
    department: 'Public Works',
    timestamp: '2023-10-24',
  },
  {
    id: 'adm-8',
    title: 'Contaminated water supply reported',
    category: 'water',
    status: 'resolved',
    location: 'Westside Residential',
    upvotes: 210,
    department: 'Water Board',
    timestamp: '2023-10-15',
  },
  {
    id: 'adm-9',
    title: 'Traffic light stuck on red',
    category: 'streetlight',
    status: 'reported',
    location: 'Downtown Square',
    upvotes: 34,
    department: 'Electrical',
    timestamp: '2023-10-25',
  },
  {
    id: 'adm-10',
    title: 'Broken park bench and playground equipment',
    category: 'other',
    status: 'acknowledged',
    location: 'Centennial Park',
    upvotes: 18,
    department: 'Parks & Rec',
    timestamp: '2023-10-21',
  },
];
