export const mockIssues = [
  {
    id: 'iss-1',
    title: 'Massive pothole on Main Street',
    category: 'pothole',
    status: 'reported',
    location: 'Main St & 4th Ave',
    upvotes: 45,
    userHasUpvoted: true,
    commentsCount: 12,
    department: 'Public Works',
    timestamp: '2 hours ago',
    description: 'There is a huge pothole spanning almost the entire left lane. Several cars have hit it hard. Needs immediate filling before someone gets into a serious accident.',
    imageUrl: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&q=80&w=800',
    isMine: false,
  },
  {
    id: 'iss-2',
    title: 'Overflowing dumpster behind complex',
    category: 'garbage',
    status: 'acknowledged',
    location: 'Sector 4, Market area',
    upvotes: 32,
    userHasUpvoted: false,
    commentsCount: 5,
    department: 'Sanitation',
    timestamp: '5 hours ago',
    description: 'The main commercial dumpster hasn’t been emptied in over a week. Garbage is spilling into the street and attracting pests. Smells terrible.',
    imageUrl: 'https://images.unsplash.com/photo-1605600659873-d808a1d84f8c?auto=format&fit=crop&q=80&w=800',
    isMine: true,
  },
  {
    id: 'iss-3',
    title: 'Burst pipe flooding the sidewalk',
    category: 'water',
    status: 'inProgress',
    location: 'Elm Street & 2nd Ave',
    upvotes: 89,
    userHasUpvoted: true,
    commentsCount: 24,
    department: 'Water Board',
    timestamp: '1 day ago',
    description: 'Water is gushing out of a cracked pipe under the pavement. It’s flooding the pedestrian walkway and freezing over at night, making it very dangerous.',
    imageUrl: 'https://images.unsplash.com/photo-1542037104857-ffbb0b9155fb?auto=format&fit=crop&q=80&w=800',
    isMine: false,
  },
  {
    id: 'iss-4',
    title: 'Streetlights out for 3 blocks',
    category: 'streetlight',
    status: 'resolved',
    location: 'Oak Drive, North side',
    upvotes: 12,
    userHasUpvoted: false,
    commentsCount: 2,
    department: 'Electrical',
    timestamp: '2 days ago',
    description: 'The streetlights have been out for several nights, making it unsafe to walk in the evening.',
    imageUrl: null,
    isMine: true,
  },
  {
    id: 'iss-5',
    title: 'Fallen tree blocking intersection',
    category: 'other',
    status: 'reported',
    location: 'Pine Blvd & 5th St',
    upvotes: 67,
    userHasUpvoted: false,
    commentsCount: 8,
    department: 'Parks & Rec',
    timestamp: '3 days ago',
    description: 'A large oak tree fell during the storm last night and is completely blocking the intersection.',
    imageUrl: null,
    isMine: false,
  },
  {
    id: 'iss-6',
    title: 'Illegal dumping near the river',
    category: 'garbage',
    status: 'inProgress',
    location: 'River Road, East bank',
    upvotes: 104,
    userHasUpvoted: true,
    commentsCount: 31,
    department: 'Sanitation',
    timestamp: '4 days ago',
    description: 'Someone dumped a truckload of construction debris right next to the river trail.',
    imageUrl: null,
    isMine: true,
  },
  {
    id: 'iss-7',
    title: 'Traffic light stuck on red',
    category: 'streetlight',
    status: 'reported',
    location: 'Downtown Square',
    upvotes: 34,
    userHasUpvoted: false,
    commentsCount: 4,
    department: 'Electrical',
    timestamp: '1 week ago',
    description: 'The eastbound traffic light is stuck on red, causing massive backups during rush hour.',
    imageUrl: null,
    isMine: false,
  },
  {
    id: 'iss-8',
    title: 'Broken park bench and playground equipment',
    category: 'other',
    status: 'acknowledged',
    location: 'Centennial Park',
    upvotes: 18,
    userHasUpvoted: false,
    commentsCount: 1,
    department: 'Parks & Rec',
    timestamp: '2 weeks ago',
    description: 'The swings are broken and one of the main benches has collapsed. Needs repair before spring.',
    imageUrl: null,
    isMine: false,
  }
];
